JamesBondGadgetsEntity/Controllers/GadgetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JamesBondGadgetsEntity;
using JamesBondGadgetsEntity.Models;

namespace JamesBondGadgetsEntity.Controllers
{
    public class GadgetsController : Controller
    {
        private ApplicationDbContext context;

        public GadgetsController()
        {
            context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }
        // GET: Gadgets
        public ActionResult Index()
        {
            List<GadgetsModel> gadgets = context.Gadgets.ToList();

            return View("Index", gadgets);
        }

        public ActionResult Details(int id)
        {
            GadgetsModel gadgets = context.Gadgets.SingleOrDefault(g => g.Id == id);
            return View("Details", gadgets);
        }

        public ActionResult Create()
        {
            return View("GadgetForm", new GadgetsModel());
        }

        public ActionResult Edit(int id)
        {
            GadgetsModel gadgets = context.Gadgets.SingleOrDefault(g => g.Id == id);

            return View("GadgetForm", gadgets);
        }

        public ActionResult Delete(int id)
        {

            GadgetsModel gadgets = context.Gadgets.SingleOrDefault(g => g.Id == id);

            context.Entry(gadgets).State = System.Data.Entity.EntityState.Deleted;
            context.SaveChanges();

            return View("Deleteq");
        }
        public ActionResult ProcessCreate(GadgetsModel gadgetsModel)
        {
            GadgetsModel gadgets = context.Gadgets.SingleOrDefault(g => g.Id == gadgetsModel.Id);

            //edit
            if(gadgets != null)
            {
                gadgets.Name = gadgetsModel.Name;
                gadgets.Description = gadgetsModel.Description;
                gadgets.AppearsIn = gadgetsModel.AppearsIn;
                gadgets.WithThisActor = gadgetsModel.WithThisActor;

               
            }
            //create
            else
            {
                context.Gadgets.Add(gadgetsModel);
            }
            context.SaveChanges();

            return View("Details", gadgetsModel);
        }
        public ActionResult SearchForm()
        {
            return View("SearchForm");
        }

        public ActionResult SearchForName(string searchPhrase)
        {
            var gadgets = from g in context.Gadgets where g.Name.Contains(searchPhrase) select g;

            return View("Index", gadgets);
        }
    }
}

JamesBondGadgetsEntity/Views/Gadgets/Deleteq.cshtml
@model JamesBondGadgetsEntity.Models.GadgetsModel

@{
    ViewBag.Title = "Deleteq";
}

<h2>Deleteq</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GadgetsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppearsIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppearsIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WithThisActor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WithThisActor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JamesBondGadgetsEntity/Views/Gadgets/Details.cshtml
@model JamesBondGadgetsEntity.Models.GadgetsModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>GadgetsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppearsIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppearsIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WithThisActor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WithThisActor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JamesBondGadgetsEntity/Views/Gadgets/GadgetForm.cshtml
@model JamesBondGadgetsEntity.Models.GadgetsModel

@{
    ViewBag.Title = "GadgetForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GadgetForm</h2>


@using (Html.BeginForm("ProcessCreate", "Gadgets")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>GadgetsModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AppearsIn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AppearsIn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AppearsIn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WithThisActor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.WithThisActor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WithThisActor, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Id)
    @*<input type="hidden" name="Id" value="@Model.Id" />*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JamesBondGadgetsEntity/Views/Gadgets/Index.cshtml
@model IEnumerable<JamesBondGadgetsEntity.Models.GadgetsModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AppearsIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WithThisActor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AppearsIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WithThisActor)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

JamesBondGadgetsEntity/Views/Gadgets/SearchForName.cshtml
@model IEnumerable<JamesBondGadgetsEntity.Models.GadgetsModel>

@{
    ViewBag.Title = "SearchForName";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SearchForName</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AppearsIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WithThisActor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AppearsIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WithThisActor)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

JamesBondGadgetsEntity/Views/Gadgets/SearchForm.cshtml
@model JamesBondGadgetsEntity.Models.GadgetsModel

@{
    ViewBag.Title = "SearchForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SearchForm</h2>


@using (Html.BeginForm("SearchForName","Gadgets"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GadgetsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                <label for="searchPhrase">Search in name</label>
                <input type="text" name="searchPhrase" id="searchPhrase" class="form-control" />

            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}